export const FETCH_ARTICLE_REQUEST = "FETCH_ARTICLE_REQUEST";
export const FETCH_ARTICLE_SUCCESS = "FETCH_ARTICLE_SUCCESS";
export const FETCH_ARTICLE_SUCCESS_EMPTY_RESULT = "FETCH_ARTICLE_EMPTY_RESULT";
export const FETCH_ARTICLE_FAILURE = "FETCH_ARTICLE_FAILURE";


export const SET_ARTICLE_QUERTY_PARAMS = "SET_ARTICLE_QUERTY_PARAMS";

export const QUERTY_INPUT_CHANGE = "QUERTY_INPUT_CHANGE";
export const FROM_DATE_CHANGE = "FROM_DATE_CHANGE";
export const TO_DATE_CHANGE = "TO_DATE_CHANGE";
